#!/bin/sh
DIM="chayang -d 15"
LOCK="swaylock"
swayidle -w \
    timeout 300 "$DIM && $LOCK" \
    timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
    before-sleep "$LOCK" \
    lock "$LOCK"

