#: once we have starship > 0.58, we can have right_prompt...
# format = """$character"""
# right_format = """$all"""
# [line_break]
# disabled = true

add_newline = false
command_timeout = 250
right_format = ""

[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
show_milliseconds = true

[conda]
disabled = true

[directory]
read_only = " \uf83d"
truncate_to_repo = false
truncation_length = -1

[gcloud]
disabled = true

[status]
disabled = false
symbol = ""

