#: once we have starship > 0.58, we can have right_prompt...
# format = """$character"""
# right_format = """$all"""
# [line_break]
# disabled = true

# format = ""
add_newline = false
command_timeout = 250
right_format = ""

[aws]
disabled = true
symbol = "aws "

[battery]
disabled = true

[cmd_duration]
#show_milliseconds = true
#show_notifications = true
format = 'took [$duration]($style) '

[conda]
disabled = true
symbol = "conda "

[directory]
read_only = " ro"
truncate_to_repo = false
truncation_length = -1

[gcloud]
disabled = true

[status]
disabled = false
format = "[$status]($style) "



### plaintext everything...
[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[bun]
symbol = "bun "

[c]
symbol = "C "

[cobol]
symbol = "cobol "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "
disabled = false

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[raku]
symbol = "raku "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "

